deployment: development

database:
  host: ""
  port: 5432
  user: ""
  password: ""
  database: ""
  scheme: ""
  migrationPath: "../../migrations"

logging:
  level: debug
  prettyPrint: true

monitorserver:
  host: 0.0.0.0
  port: 4445

